### ISSUE TITLE
how to build from github repo

### ISSUE THREAD

**Issue by devel-chm** [nrdvana/perl-X11-GLX#1]
I was unable to build from cpan due to some failing tests:

> PERL_DL_NONLAZY=1 "/usr/bin/perl.exe" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/01-load-module.t ....... ok
t/02-std-functions.t ..... ok
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  149 (GLX)
  Minor opcode of failed request:  3 (X_GLXCreateContext)
  Value in failed request:  0x0
  Serial number of failed request:  826
  Current serial number in output stream:  829
t/03-import-context.t .... 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 4/11 subtests 
C-style XGetGeometry is deprecated; use 2 arguments to return a list, instead at /home/chm/local64/lib/perl5/cygwin-thread-multi/X11/Xlib/Window.pm line 9.
C-style XGetGeometry is deprecated; use 2 arguments to return a list, instead at /home/chm/local64/lib/perl5/cygwin-thread-multi/X11/Xlib/Window.pm line 9.
t/05-dwim.t .............. ok
t/author-pod-coverage.t .. skipped: these tests are for testing by the author
t/author-pod-syntax.t .... skipped: these tests are for testing by the author
> 
> Test Summary Report
> -------------------
> t/03-import-context.t  (Wstat: 256 Tests: 7 Failed: 0)
>   Non-zero exit status: 1
>   Parse errors: Bad plan.  You planned 11 tests but ran 7.
> Files=6, Tests=17,  3 wallclock secs ( 0.01 usr  0.03 sys +  0.85 cusr  1.59 csys =  2.49 CPU)
Result: FAIL
Failed 1/6 test programs. 0/17 subtests failed.
make: *** [Makefile:1067: test_dynamic] Error 255
(/usr/bin/make test exited with 512)

and it appears that the github repository is missing some Makefile.PL
magic for building and development from there.  If the build problems
can be resolved, it seems that this module might be used to implement
OpenGL::GLX to spin off the GLX/X11 specific components of OpenGL.

This is needed because the work to implement OpenGL::Modern is
trying to clean up the mess of multiple default required APIs.  We've
spun off GLUT and GLU and Array and I'm working on OpenGL::GLFW
bindings.

**Comment by nrdvana** [comment]
Hi!  First off, I'd be grateful for any additional developer effort on this module.  I sank quite a bit of my free time into it this spring, and sort of burned out, though I'm certainly not done.

I'd suspect the error above is related to insufficient feature-detection of the X server.  glXCreateContext is the older API prior to glXCreateNewContext, and I thought it was supported everywhere, but maybe has been removed from your implementation?

This module is built with Dist::Zilla.  So, you should be able to use "cpanm Dist::Zilla; dzil build" to get it working.  The tool is a bit heavyweight (sorry) but removes most of the busywork from releasing dists, especially the stuff I usually screw up, like getting the version number updated, and running a clean test without leftover files from earlier builds.  This module is harder than most to integrate with Dist::Zilla, because of XS and depending on C library exports from X11::Xlib, so I actually have a large chunk of Makefile.PL hand-written in [Makefile.header](../blob/master/Makefile.header)

**Comment by devel-chm** [comment]
I was very happy to see X11::GLX appear.  It seems pretty close to including the needed functionality since my main need is to provide (at least) back compatibility with the various GLX functions and X11 constants needed in the perl OpenGL module.  The goal is that OpenGL::Modern does OpenGL only and the contexts are provided by some provider (OpenGL::GLUT, OpenGL::GLFW, Prima::OpenGL,...).

**Comment by nrdvana** [comment]
BTW, I agree that OpenGL::GLX is probably a better namespace than X11::GLX, because the glx functions are located in libGL.so   But, when I was planning it out I realized that I'd need to use almost all of the boilerplate I developed for X11::Xlib, and that maybe some day it will be possible for GLX to be based on libxcb.so, so I stuck it in the X11 namespace.  If you want to make a wrapper around my wrapper, that works.  Or if you want some API changes so that X11::GLX can be your wrapper, let me know.

**Comment by devel-chm** [comment]
After installing Dist::Zilla, I was able to build and test the latest git:

> perl-X11-GLX/X11-GLX-0.03 $
 make test
Running Mkbootstrap for X11::GLX ()
chmod 644 "GLX.bs"
PERL_DL_NONLAZY=1 "/usr/bin/perl.exe" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/01-load-module.t ........... ok   
t/02-std-functions.t ......... ok   
t/03-import-context.t ........ \# X11 error: X11::Xlib::XErrorEvent=SCALAR(0x600783748)
\# X11 error: X11::Xlib::XErrorEvent=SCALAR(0x600078378)
t/03-import-context.t ........ skipped: Import context testing requires X Server that allows indirect contexts
t/04-fbconfig.t .............. ok    
t/30-dwim.t .................. ok   
t/31-dwim-transparent-win.t .. ok   
t/70-compositor.t ............ skipped: Work in Progress
t/author-pod-coverage.t ...... skipped: these tests are for testing by the author
t/author-pod-syntax.t ........ skipped: these tests are for testing by the author
All tests successful.
Files=9, Tests=50,  6 wallclock secs ( 0.00 usr  0.05 sys +  1.57 cusr  2.99 csys =  4.61 CPU)
Result: PASS

and everything passes.  I'm not sure about the two X11 errors reported.

**Comment by nrdvana** [comment]
I've added instructions to the README regarding the dist::zilla tool, to prevent future confusion.
